url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# Open Graph Specific Tags
open-graph:
  type: ""
  image: ""

twitter:
  type: "" #The card type, which will be one of “summary”, “summary_large_image”, “app”, or “player”.
  id: "2582378478"

  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# fontawesome: "https://kit.fontawesome.com/9eb6b1689c.js"

# material-icon: "https://fonts.googleapis.com/icon?family=Material+Icons"

# google-font: 

# isPWA: true

# swup-animation: "https://unpkg.com/swup@latest/dist/swup.min.js"

sass:
  style: compressed # possible values: nested expanded compact compressed

stylesheet: # place external url here